# Generated by Django 3.1.4 on 2020-12-30 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address_country', models.CharField(max_length=20)),
                ('address_province', models.CharField(max_length=20)),
                ('address_city', models.CharField(max_length=30)),
                ('address_zone', models.CharField(max_length=30)),
                ('address_neighnorhood', models.CharField(max_length=30)),
                ('address_street', models.CharField(max_length=30)),
                ('address_buildingNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('category_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_FirstName', models.CharField(max_length=20)),
                ('customer_LastName', models.CharField(max_length=20)),
                ('customer_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.address')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('order_amount', models.FloatField()),
                ('order_descount', models.FloatField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.address')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.customer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=20)),
                ('shop_description', models.CharField(max_length=40)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.address')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('producotOrder_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('productOrder_subototasl', models.FloatField()),
                ('productOrder_discount', models.FloatField()),
                ('productOrder_total', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=20)),
                ('product_price', models.FloatField()),
                ('product_descount', models.FloatField()),
                ('product_stock', models.IntegerField()),
                ('product_isOffer', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.category')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('phone_provider', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.shop'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.user'),
        ),
    ]
