# Generated by Django 3.1.4 on 2020-12-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_street',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_FirstName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_LastName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=60),
        ),
    ]
