# Generated by Django 2.2.18 on 2021-02-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20201231_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='producotOrder_id',
            new_name='productOrder_id',
        ),
        migrations.RenameField(
            model_name='productorder',
            old_name='productOrder_subototasl',
            new_name='productOrder_subtotal',
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(default='blanco', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_gender',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_isHighlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(default='L', max_length=5),
            preserve_default=False,
        ),
    ]
