# Generated by Django 3.1.4 on 2021-02-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='user_is_admin',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_buildingNo',
            field=models.IntegerField(default=False),
        ),
    ]
