# Generated by Django 3.1.4 on 2021-02-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_auto_20210202_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
