# Generated by Django 3.1.4 on 2021-02-03 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0006_product_product_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_fecha',
            field=models.DateField(default=datetime.date(2021, 2, 3)),
        ),
    ]
