# Generated by Django 3.1.4 on 2021-02-03 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0007_auto_20210203_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_country',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
