# Generated by Django 3.1.4 on 2021-02-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0008_auto_20210203_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_fecha']},
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone_provider',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=40),
        ),
    ]
